'use strict';
const bcrypt = require('bcrypt')

module.exports = {
  async up(queryInterface) {

    await queryInterface.bulkInsert('Users', [{
      username: 'Юлия',
      email: 'juliya@mail.ru',
      birth_date: '1992-03-03',
      avatar: '/avatars/2022-08-24_12.06.45.png',
      gender: 'Ж',
      bio: 'Читаю, играю на пианино, люблю рисовать, люблю музыку, природу, кофе со сливками и выращивать цветы.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Марина',
      email: 'marina@mail.ru',
      birth_date: '1996-05-01',
      avatar: '/avatars/2022-08-24_12.07.29.png',
      gender: 'Ж',
      bio: 'Буду рада общению, друзьям и отношениям :)',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Алина',
      email: 'alina@mail.ru',
      birth_date: '1992-06-11',
      avatar: '/avatars/2022-08-24_12.08.08.png',
      gender: 'Ж',
      bio: 'Интроверт. Часто путешествую, работаю на себя удаленно. Изначальная цель - общение. Если это приведет к чему-то большему, буду только рада.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Kseniya',
      email: 'kseniya@mail.ru',
      birth_date: '1998-02-01',
      avatar: '/avatars/2022-08-24_12.08.39.png',
      gender: 'Ж',
      bio: 'Привет! Предпочитаю общаться с прямыми и искренними людьми, которые также хорошо относятся к животным. О себе: люблю природу, динамичный спорт, исследование других городов и стран, живую музыку, познавать новое, IT.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Ольга',
      email: 'olga@mail.ru',
      birth_date: '1993-08-01',
      avatar: '/avatars/2022-08-24_12.09.02.png',
      gender: 'Ж',
      bio: 'Опыт нахождения на этой площадке доказал, что здесь есть классные, увлеченные, мыслящие люди! Жизнь одна, кайфуйте!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Максим',
      email: 'maksim@mail.ru',
      birth_date: '2000-02-01',
      avatar: '/avatars/M2022-08-24_12.13.01.png',
      gender: 'М',
      bio: 'Специалист по ИТ-технологиям. Ищу интересную девушку любой внешности. Обожаю прогулки по вечерам и спорт, слабость – вкусная домашняя еда',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Пётр',
      email: 'petr@mail.ru',
      birth_date: '1994-01-01',
      avatar: '/avatars/M2022-08-24_12.13.49.png',
      gender: 'М',
      bio: 'Моя жизнь полна интересных событий. Единственное, чего мне не хватает – любимая девушка рядом. Я разделил бы с ней эту насыщенную жизнь, поэтому и решил завести здесь анкету. В интернете гораздо проще познакомиться с интересным собеседником',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Александр',
      email: 'aleksandr@mail.ru',
      birth_date: '1991-01-01',
      avatar: '/avatars/M2022-08-24_12.14.45.png',
      gender: 'М',
      bio: 'Я тут первый раз и не знаю, что писать. Всем хай!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Даниил',
      email: 'daniil@mail.ru',
      birth_date: '1990-01-01',
      avatar: '/avatars/M2022-08-24_12.15.33.png',
      gender: 'М',
      bio: 'Привет всем! Люблю музыку, концерты, вечеринки и другой драйв! Хотел бы совместить это с личной жизнью, поэтому я тут.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Георгий',
      email: 'georgiy@mail.ru',
      birth_date: '1985-06-01',
      avatar: '/avatars/M2022-08-24_12.16.44.png',
      gender: 'М',
      bio: 'Не люблю спорт – вместо этого я трачу время на инвестиции в будущее, которое мечтаю разделить с тобой. Кстати, я имел в виду просмотр футбола, концерты и всё остальное, что можно делать совместно',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      username: 'Виталий',
      email: 'vitaliy@mail.ru',
      birth_date: '1993-04-01',
      avatar: '/avatars/vitaliy.png',
      gender: 'М',
      bio: 'Всем привет! Интересно поюзать приложение, которое сами писали. Как будто бы всё работает.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Поля',
      email: 'polya@mail.ru',
      birth_date: '1996-08-12',
      avatar: '/avatars/polya.png',
      gender: 'Ж',
      bio: 'Всем привет! Интересно поюзать приложение, которое сами писали. Я team-lead, если че.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Саша',
      email: 'sasha_a@mail.ru',
      birth_date: '1986-07-04',
      avatar: '/avatars/sasha_a.png',
      gender: 'М',
      bio: 'Всем привет! Интересно поюзать приложение, которое сами писали. Очень понравилось работать над проектом.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Мари',
      email: 'mari@mail.ru',
      birth_date: '1998-08-12',
      avatar: '/avatars/mari.png',
      gender: 'Ж',
      bio: 'Всем привет! Интересно поюзать приложение, которое сами писали. Кому понравилась верстка, жмите лайк.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Катя',
      email: 'katya@mail.ru',
      birth_date: '1999-08-12',
      avatar: '/avatars/katya.png',
      gender: 'Ж',
      bio: 'Всем привет! Скоро закончится обучение в Elbrus,  я уеду и буду очень скучать.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Серёга',
      email: 'serega@mail.ru',
      birth_date: '1996-08-12',
      avatar: '/avatars/serega.png',
      gender: 'М',
      bio: 'Всем привет! Я часто всем помогаю и за это мне постоянно говорят "Cпасибо" на стендапах.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Антон',
      email: 'anton@mail.ru',
      birth_date: '1986-08-12',
      avatar: '/avatars/anton.png',
      gender: 'М',
      bio: 'Всем привет! Я team-lead крутого проекта про активный отдых, ставь лайк',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Паша',
      email: 'pasha_s@mail.ru',
      birth_date: '1993-08-12',
      avatar: '/avatars/pasha_s.png',
      gender: 'М',
      bio: 'Всем привет! Я запилил с командой проект про активный отдых, в свободное время играю на музыкальных инструментах.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Лёха',
      email: 'leha@mail.ru',
      birth_date: '1995-08-12',
      avatar: '/avatars/leha.png',
      gender: 'М',
      bio: 'Всем привет! Я team-lead крутого проекта по доставке суши и роллов в Саратове, ставь лайк.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Юра',
      email: 'yura@mail.ru',
      birth_date: '1995-08-12',
      avatar: '/avatars/yura.png',
      gender: 'М',
      bio: 'Всем привет! Я запилил проект c Лёхой, а еще занимаюсь организацией выпускного, поэтому ставь лайк и сдавай деньги.',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Марк',
      email: 'mark@mail.ru',
      birth_date: '1990-08-12',
      avatar: '/avatars/mark.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Дамир',
      email: 'damir@mail.ru',
      birth_date: '1995-08-12',
      avatar: '/avatars/damir.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Паша',
      email: 'pasha_e@mail.ru',
      birth_date: '1979-08-12',
      avatar: '/avatars/pasha_e.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Саша',
      email: 'sasha_s@mail.ru',
      birth_date: '1988-08-12',
      avatar: '/avatars/sasha_s.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Артём',
      email: 'artem@mail.ru',
      birth_date: '1993-08-12',
      avatar: '/avatars/artem.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Артём',
      email: 'p_artem@mail.ru',
      birth_date: '1988-08-12',
      avatar: '/avatars/p_artem.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Юра',
      email: 'p_yura@mail.ru',
      birth_date: '1990-08-12',
      avatar: '/avatars/p_yura.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Лена',
      email: 'p_lena@mail.ru',
      birth_date: '1993-08-12',
      avatar: '/avatars/p_lena.png',
      gender: 'Ж',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Лёша',
      email: 'p_lesha@mail.ru',
      birth_date: '1989-08-12',
      avatar: '/avatars/p_lesha.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Аня',
      email: 'p_anya@mail.ru',
      birth_date: '1992-08-12',
      avatar: '/avatars/p_anya.png',
      gender: 'Ж',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      username: 'Толя',
      email: 'p_tolya@mail.ru',
      birth_date: '1988-08-12',
      avatar: '/avatars/p_tolya.png',
      gender: 'М',
      bio: 'Всем привет!',
      city: 'Санкт-Петербург',
      password: await bcrypt.hash('123456Qq', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    },

  ], {});

  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('People', null, {});
  }
};
